# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

baseurl: /austinbitdevs.com

sass:
  sass_dir: assets/css
  style: :compressed

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "Austin Bitcoin Developers"
description: "Austin Bitcoin Developers is a meetup devoted to the research and development of Bitcoin."

# Leave out some files
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.sass-cache']

